### ISSUE TITLE
Evaluate the scalability of the new analysis

### ISSUE THREAD

**Issue by sebinside** [PalladioSimulator/Palladio-Addons-DataFlowConfidentiality-Analysis#29]
The Scalability of the new analysis should be evaluated and compared to the older Prolog-based analysis. This requires no complex models or constraints, but the input models should be big (and probably generated).

Features that need to be implemented for the analysis:
- [x] Legacy support of EMF Profiles (either via ProfilesAPI or manually)
- [x] Testing and implementation of new node characteristics metamodel (see #45 )
- [x] (Allow continuing tests from predefined scalar)

Elements that can be scaled:
- [x] Number of sequential data flow nodes with a certain number of data flow variables
- [x] Number of SetVariableActions
- [x] Number of SEFF calls with data flow variables (variable count)
- [x] Number of data flow variables
- [x] Number of node characteristics
- [x] Branches

What can be measured:
- Java: Sequence finding time + propagation time
- Prolog: Transformation to prolog program + solving

Final task:
- [ ] Move scalability tests from this repository to a [repository of the FluidTrust organization](https://github.com/FluidTrust/ConfidentialityAnalysis-ScalabilityEvaluation)

**Comment by Entenwilli** [comment]
After some more work and debugging, we are now able to generate models with applied EMF Profiles. For the analysis to use the new method to assign node characteristics, the bundles should be added to the feature first. After that the analysis needs to be updated to use the new node assignment method.

Furthermore, we can finally begin to create more testcases outlined above

**Comment by Entenwilli** [comment]
Code moved to [here](https://github.com/FluidTrust/ConfidentialityAnalysis-ScalabilityEvaluation) to keep the code out of the main repository
