### ISSUE TITLE
Add sources to the installation file

### ISSUE THREAD

**Issue by sebinside** [PalladioSimulator/Palladio-Addons-DataFlowConfidentiality-Analysis#32]
At least all PCM sources should be also downloaded using the installation file.

**Comment by Entenwilli** [comment]
@majuwa Does the Metamodel include sources that i should include in the installation file? It seems like the update site does not provide the sources to be downloaded

**Comment by sebinside** [comment]
@Entenwilli I encountered another problem in my installation: The EMP Profiles for the Node Characteristics Annotations do not get loaded correctly (see the attached screenshot). Also, when looking at the resource environment, e.g., of the `InternationalOnlineShop`, the green annotations are not visible. I remember that @majuwa already had this problem, at least in my older installation, it only seldom appeared.

![image](https://user-images.githubusercontent.com/7331248/209974751-8020993b-e850-4d3d-a5cb-fd1d98369ce2.png)

**Comment by Entenwilli** [comment]
The issue with Node Characteristic Assignments now showing up in the Editor is related to the change to the new version of the modelling repository. It seems there is an issue with the applying or retrieving a profile in the modelling project. This may also lead to the error above, as the profiles are not applied correctly.

This can be observed by opening a modelling project, opening an file with an existing *.characteristics file and trying to create a new assignment of a Node Characteristic. The editor will silently fail and you can find this in the error log:
```
java.lang.NullPointerException: Cannot invoke "org.modelversioning.emfprofile.Profile.getName()" because "profile" is null
	at org.palladiosimulator.mdsdprofiles.api.ProfileAPI.isProfileApplied(ProfileAPI.java:125)
```

**Comment by sebinside** [comment]
If I understand correctly, this only affects assignments created with earlier versions of the modeling projects and should not persist, e.g., if you make a fresh Palladio model? This should then work for most of the use cases.

**Comment by Entenwilli** [comment]
In my testing, it also applied to models newly created with the new version of the modelling project. The issue seems to be deeper in the modelling project (or it's dependencies)

**Comment by sebinside** [comment]
This is scary. We should discuss in the next meeting with @majuwa how to deal with it. Ignoring seemed to work fine until now but I'm not sure whether this is the way to go.

**Comment by majuwa** [comment]
I think there was some code in the old analysis, which forces the loading of the profiles, similar to the thing in the stand-alone initialiser. Maybe we could add an initialisation Plugin at the start-up of eclipse.

**Comment by sebinside** [comment]
@Nicolas-Boltz will have a look at the modeling repo sources

**Comment by sebinside** [comment]
Let's move the discussion about the profiles to #35. After adding the modeling repo sources, this PR can be merged.

**Comment by majuwa** [comment]
@Entenwilli if this [pr](https://github.com/PalladioSimulator/Palladio-Addons-DataFlowConfidentiality-Metamodel/pull/4) is through, you can continue on this issue
