### ISSUE TITLE
EMF Profiles Alternative for Node Characteristics

### ISSUE THREAD

**Issue by sebinside** [PalladioSimulator/Palladio-Addons-DataFlowConfidentiality-Analysis#35]
As discussed in #32, EMF Profiles are sometimes not loaded correctly which becomes visible in missing annotations in the graphical editors or in errors while opening PCM models. Maybe, we can fix this after having a look in the modeling repository.

Additional resources:
https://sdq.kastel.kit.edu/wiki/EMF_Profile_Definition
https://github.com/orgs/PalladioSimulator/repositories?q=emf+profiles&type=all&language=&sort=

**Comment by sebinside** [comment]
I just had a discussion with @majuwa: Another workaround could be to support EMF Profiles in its current (partially broken) state, but use a new annotation meta model for newer models. Let's discuss this in the next meeting.

**Comment by sebinside** [comment]
Best Workaround for the EML Profiles for now:
1. Open Eclipse. If a `representations.aird` file is open, close it, do *not* save it.
2. Open a `.resourceenvironment` file that has applied characteristics in it, ignore a potential error message while opening
3. Navigate to a element that should have characteristics
4. Right mouse click, go to `MDSD Profiles...`, click on `Apply/Unapply` profiles
5. Close the file and reopen the `representations.aird`. Now, the characteristics should become visible (here, and in all other files)

**Comment by sebinside** [comment]
Helpful link: https://www.vogella.com/tutorials/EclipseEMF/article.html

**Comment by sebinside** [comment]
Our solution: Support EMF Profiles with the workaround mentioned [above](https://github.com/PalladioSimulator/Palladio-Addons-DataFlowConfidentiality-Analysis/issues/35#issuecomment-1378762708) and additionally support another meta model for node characteristics, see [this PR](https://github.com/PalladioSimulator/Palladio-Addons-DataFlowConfidentiality-Metamodel/pull/2).

**Comment by Entenwilli** [comment]
Fix was implemented in [this PR](https://github.com/PalladioSimulator/Palladio-Addons-DataFlowConfidentiality-Metamodel/pull/2)

**Comment by majuwa** [comment]
Unfortunately we forgot to add the new bundles to a feature and therefore the update site does not deploy it.

**Comment by Entenwilli** [comment]
The feature is now deployed in a bundle as well (see [here](https://github.com/PalladioSimulator/Palladio-Addons-DataFlowConfidentiality-Metamodel/pull/4))
