### ISSUE TITLE
Optimize performance with parallel streams

### ISSUE THREAD

**Issue by sebinside** [PalladioSimulator/Palladio-Addons-DataFlowConfidentiality-Analysis#50]
Currently, we iterate over streams sequentially, e.g., to propagate labels and to identify confidentiality violations. Regarding performance and the scalability evaluation #29, #47, we could think about using the `parallel()` option of Java streams. This could be easily possible due to our intense use of immutability. However, it shall be investigated whether this actually improves the performance (significantly) and whether there are negative side effects.

**Comment by Entenwilli** [comment]
I've determined a smaller issue while using parallel streams in the evaluation of action sequences:
For the most part, our action sequences are immutable, so using parallel streams is acceptable.
However, `DatabaseActionSequenceElement`s have a local `DataStore` object that is shared between action sequences. This allows the Database functionality, that is used in the Travel Planner example, to work.
This sharing of data, however, causes a race condition in the stream.
Overall, this leads to the following takeaways:
- Parallel streams are supported in most use cases, except where data stores are used
- A small overhead to determine dynamically whether these components are used
- Parallel operations on sequences with data stores may be hard or impossible

**Comment by sebinside** [comment]
Good observation, seems plausible, I agree with your solution 👍
