### ISSUE TITLE
Implement Label Propagation

### ISSUE THREAD

**Issue by sebinside** [PalladioSimulator/Palladio-Addons-DataFlowConfidentiality-Analysis#6]
The label propagation shall be implemented based on the new object model and the [prototypical](https://github.com/FluidTrust/Palladio-Addons-DataFlowConfidentiality-Java) propagation logic.

This shall include:
- [x] The label propagation algorithm
- [x] Support for node labels that are not propagated
- [x] Support for `.container` relations in stoex logic
- [x] Automatic testability by adjusting the maven pom (and fixing the build)

**Comment by Nicolas-Boltz** [comment]
Build is fixed: Tycho targetplatform, maven poms and manifest.MF have been modified. Palladio build pipeline action has been updated to current version. As java 17 is not supported by our self-hosted runners, currently the build is running on GitHub hosted runners.

**Comment by Entenwilli** [comment]
In the recent commits of #4 i have implemented the support for node labels that are applied from UsageScenarios and Allocations. Furthermore, the references to ´.container´ relations can be accessed

**Comment by sebinside** [comment]
Thank you, I will hopefully already be able to review the current state later today. Do we already have a test model that actually uses the `.container` reference in a stoex?

**Comment by Entenwilli** [comment]
Currently the three models we use in testing (Branching Online Shop, International Online Shop and Travel Planner) do not use the `container` reference in a stoex, i will look for One tomorrow on the other example models

**Comment by sebinside** [comment]
Very good, thank you!
